openapi: 3.0.0
info:
  title: MD5 Hash Lookup API (BrokerNitrix)
  version: "1.0"
servers:
  - url: https://prod-93.eastus.logic.azure.com:443
paths:
   /workflows/9d8f6557af2c4d458242cc2752057465/triggers/When_a_HTTP_request_is_received/paths/invoke:
     post:
      operationId: MD5HashBroker
      description: Triggers the specified Logic App workflow.
      summary: Retrieves the original value of a given MD5 hash (BrokerNitrix)
      parameters:
        - name: api-version
          in: query
          default: 2016-10-01
          schema:
            type: string
        - name: sp
          in: query
          schema:
            type: string
        - name: sv
          in: query  
          default: 1.0
          schema:
            type: string
        - name: sig
          in: query
          default: S42kf-ieED6DT5puFTIgP1gf-0NrmgYry4n4DUVQ4SI
          schema:
            type: string
      requestBody:
        description: The MD5 hash to look up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                MD5:
                  type: string
      responses:
        "200":
        description: Information about the hash, whether found or not.